# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'tkspider.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!
import sys
import os
from functools import partial
from PyQt5 import QtCore, QtGui, QtWidgets,Qt
from PyQt5.QtWidgets import QFileDialog,QListWidget
from PyQt5.QtCore import QObject,pyqtSignal,QCoreApplication
from win32com import client
cwd = os.getcwd()


class UiMainWindow(object):

    def __init__(self):
        super(UiMainWindow,self).__init__()
        self.setupUi(self)
        self.numb1 = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        desktop = QtWidgets.QApplication.desktop()
        x = (desktop.width() - 801) // 2
        y = (desktop.height() - 612) // 2
        MainWindow.move(x,y)
        MainWindow.resize(801, 612)
        MainWindow.setFixedSize(801,612)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setStyleSheet('QListWidget{border:1px solid gray; color:black; }'
                                 'QListWidget::Item{padding-top:-2px; padding-bottom:-1px;}'
                                 "QListWidget::Item:hover{background:skyblue;padding-top:0px; padding-bottom:0px; }"
                                 #"QListWidget::item:selected{background:lightpink; color:red; }"
                                 #"QListWidget::item:selected:!active{active{border-width:0px;background:lightgreen; }"
                                )

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 20, 801, 591))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 338))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(0)
        self.tabWidget.setFont(font)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setToolTipDuration(0)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setObjectName("tabWidget")

        # ##设置 通用listwidget
        # self.liwidget = QListWidget()

        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setMouseTracking(True)
        self.tab_1.setTabletTracking(True)
        self.tab_1.setObjectName("tab_1")
        self.icon1 = QtGui.QIcon()
        self.icon1.addPixmap(QtGui.QPixmap(cwd + "/ico/fpg.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.icon2 = QtGui.QIcon()
        self.icon2.addPixmap(QtGui.QPixmap(cwd + "/ico/qpg.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.widget = QtWidgets.QWidget(self.tab_1)
        self.widget.setGeometry(QtCore.QRect(0, 0, 801, 309))
        self.widget.setObjectName("widget_1")
        self.pzbt = QtWidgets.QPushButton(self.widget)
        self.pzbt.setGeometry(QtCore.QRect(710, 20, 75, 23))
        self.pzbt.setObjectName("pzbt_1")
        self.uploadbt_1 = QtWidgets.QPushButton(self.widget)
        self.uploadbt_1.setGeometry(QtCore.QRect(710, 80, 75, 23))
        self.uploadbt_1.setObjectName("uploadbt_1")
        self.label_1 = QtWidgets.QLabel(self.widget)
        self.label_1.setGeometry(QtCore.QRect(710, 270, 60, 23))
        self.label_1.setText("已下载:")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(750, 270, 40, 23))

        self.listWidget_1 = QListWidget(self.widget)
        self.listWidget_1.setGeometry(QtCore.QRect(0, 0, 691, 308))
        self.listWidget_1.setObjectName("listWidget_1")
        ## 数据模型1
        self.listWidget_1.addItems([r'D:\workspace\project\pyqt\biguo2\wantiku\集群.xlsx', r'wantiku\2013年10月《中国法制史》真题.xlsx', r"wantiku\1.xlsx"])
        self.tabWidget.addTab(self.tab_1, "0")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 801, 309))
        self.widget_2.setObjectName("widget_2")
        self.pzbt_2 = QtWidgets.QPushButton(self.widget_2)
        self.pzbt_2.setGeometry(QtCore.QRect(710, 20, 75, 23))
        self.pzbt_2.setObjectName("pzbt_2")
        self.uploadbt_2 = QtWidgets.QPushButton(self.widget_2)
        self.uploadbt_2.setGeometry(QtCore.QRect(710, 80, 75, 23))
        self.uploadbt_2.setObjectName("uploadbt_2")
        self.listWidget_2 = QListWidget(self.widget_2)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 0, 691, 308))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(710, 270, 60, 23))
        self.label_2.setText("已下载:")
        self.label_22 = QtWidgets.QLabel(self.widget_2)
        self.label_22.setGeometry(QtCore.QRect(750, 270, 40, 23))
        self.label_22.setText("-----")

        self.tabWidget.addTab(self.tab_2, "1")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widget_3 = QtWidgets.QWidget(self.tab_3)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 801, 309))
        self.widget_3.setObjectName("widget_3")
        self.pzbt_3 = QtWidgets.QPushButton(self.widget_3)
        self.pzbt_3.setGeometry(QtCore.QRect(710, 20, 75, 23))
        self.pzbt_3.setObjectName("pzbt_3")
        self.uploadbt_3 = QtWidgets.QPushButton(self.widget_3)
        self.uploadbt_3.setGeometry(QtCore.QRect(710, 80, 75, 23))
        self.uploadbt_3.setObjectName("uploadbt_3")
        self.listWidget_3 = QListWidget(self.widget_3)
        self.listWidget_3.setGeometry(QtCore.QRect(0, 0, 691, 308))
        self.listWidget_3.setObjectName("listWidget_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(710, 270, 60, 23))
        self.label_3.setText("已下载:")
        self.label_33 = QtWidgets.QLabel(self.widget_3)
        self.label_33.setGeometry(QtCore.QRect(750, 270, 40, 23))
        self.label_33.setText("-----")

        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget_4 = QtWidgets.QWidget(self.tab_4)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 801, 309))
        self.widget_4.setObjectName("widget_4")
        self.pzbt_4 = QtWidgets.QPushButton(self.widget_4)
        self.pzbt_4.setGeometry(QtCore.QRect(710, 20, 75, 23))
        self.pzbt_4.setObjectName("pzbt_4")
        self.uploadbt_4 = QtWidgets.QPushButton(self.widget_4)
        self.uploadbt_4.setGeometry(QtCore.QRect(710, 80, 75, 23))
        self.uploadbt_4.setObjectName("uploadbt_4")
        self.listWidget_4 = QListWidget(self.widget_4)
        self.listWidget_4.setGeometry(QtCore.QRect(0, 0, 691, 308))
        self.listWidget_4.setObjectName("listWidget_4")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(710, 270, 60, 23))
        self.label_4.setText("已下载:")
        self.label_44 = QtWidgets.QLabel(self.widget_4)
        self.label_44.setGeometry(QtCore.QRect(750, 270, 40, 23))
        self.label_44.setText("-----")

        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.widget_5 = QtWidgets.QWidget(self.tab_5)
        self.widget_5.setGeometry(QtCore.QRect(0, 0, 801, 309))
        self.widget_5.setObjectName("widget_5")
        self.pzbt_5 = QtWidgets.QPushButton(self.widget_5)
        self.pzbt_5.setGeometry(QtCore.QRect(710, 20, 75, 23))
        self.pzbt_5.setObjectName("pzbt_5")
        self.uploadbt_5 = QtWidgets.QPushButton(self.widget_5)
        self.uploadbt_5.setGeometry(QtCore.QRect(710, 80, 75, 23))
        self.uploadbt_5.setObjectName("uploadbt_5")
        self.listWidget_5 = QListWidget(self.widget_5)
        self.listWidget_5.setGeometry(QtCore.QRect(0, 0, 691, 308))
        self.listWidget_5.setObjectName("listWidget_5")
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        self.label_5.setGeometry(QtCore.QRect(710, 270, 60, 23))
        self.label_5.setText("已下载:")
        self.label_55 = QtWidgets.QLabel(self.widget_5)
        self.label_55.setGeometry(QtCore.QRect(750, 270, 40, 23))
        self.label_55.setText("-----")

        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.widget_6 = QtWidgets.QWidget(self.tab_6)
        self.widget_6.setGeometry(QtCore.QRect(0, 0, 801, 309))
        self.widget_6.setObjectName("widget_6")
        self.pzbt_6 = QtWidgets.QPushButton(self.widget_6)
        self.pzbt_6.setGeometry(QtCore.QRect(710, 20, 75, 23))
        self.pzbt_6.setObjectName("pzbt_6")
        self.uploadbt_6 = QtWidgets.QPushButton(self.widget_6)
        self.uploadbt_6.setGeometry(QtCore.QRect(710, 80, 75, 23))
        self.uploadbt_6.setObjectName("uploadbt_6")
        self.listWidget_6 = QListWidget(self.widget_6)
        self.listWidget_6.setGeometry(QtCore.QRect(0, 0, 691, 308))
        self.listWidget_6.setObjectName("listWidget_6")
        self.label_6 = QtWidgets.QLabel(self.widget_6)
        self.label_6.setGeometry(QtCore.QRect(710, 270, 60, 23))
        self.label_6.setText("已下载:")
        self.label_66 = QtWidgets.QLabel(self.widget_6)
        self.label_66.setGeometry(QtCore.QRect(750, 270, 40, 23))
        self.label_66.setText("-----")

        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.widget_7 = QtWidgets.QWidget(self.tab_7)
        self.widget_7.setGeometry(QtCore.QRect(0, 0, 801, 309))
        self.widget_7.setObjectName("widget_7")
        self.pzbt_7 = QtWidgets.QPushButton(self.widget_7)
        self.pzbt_7.setGeometry(QtCore.QRect(710, 20, 75, 23))
        self.pzbt_7.setObjectName("pzbt_7")
        self.uploadbt_7 = QtWidgets.QPushButton(self.widget_7)
        self.uploadbt_7.setGeometry(QtCore.QRect(710, 80, 75, 23))
        self.uploadbt_7.setObjectName("uploadbt_7")
        self.listWidget_7 = QListWidget(self.widget_7)
        self.listWidget_7.setGeometry(QtCore.QRect(0, 0, 691, 308))
        self.listWidget_7.setObjectName("listWidget_7")
        self.label_7 = QtWidgets.QLabel(self.widget_7)
        self.label_7.setGeometry(QtCore.QRect(710, 270, 60, 23))
        self.label_7.setText("已下载:")
        self.label_77 = QtWidgets.QLabel(self.widget_7)
        self.label_77.setGeometry(QtCore.QRect(750, 270, 40, 23))
        self.label_77.setText("-----")

        self.tabWidget.addTab(self.tab_7, "")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(0, 330, 801, 71))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.checkBox1 = QtWidgets.QCheckBox(self.frame)
        self.checkBox1.setGeometry(QtCore.QRect(20, 10, 71, 16))
        self.checkBox1.setObjectName("checkBox1")
        self.checkBox3 = QtWidgets.QCheckBox(self.frame)
        self.checkBox3.setGeometry(QtCore.QRect(170, 10, 71, 16))
        self.checkBox3.setObjectName("checkBox3")
        self.checkBox5 = QtWidgets.QCheckBox(self.frame)
        self.checkBox5.setGeometry(QtCore.QRect(340, 10, 71, 16))
        self.checkBox5.setObjectName("checkBox5")
        self.checkBox6 = QtWidgets.QCheckBox(self.frame)
        self.checkBox6.setGeometry(QtCore.QRect(410, 10, 71, 16))
        self.checkBox6.setObjectName("checkBox6")
        self.checkBox4 = QtWidgets.QCheckBox(self.frame)
        self.checkBox4.setGeometry(QtCore.QRect(250, 10, 71, 16))
        self.checkBox4.setObjectName("checkBox4")
        self.checkBox7 = QtWidgets.QCheckBox(self.frame)
        self.checkBox7.setGeometry(QtCore.QRect(500, 10, 71, 16))
        self.checkBox7.setObjectName("checkBox7")
        self.checkBox2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox2.setGeometry(QtCore.QRect(90, 10, 71, 16))
        self.checkBox2.setObjectName("checkBox2")
        self.stbt = QtWidgets.QPushButton(self.frame)
        self.stbt.setGeometry(QtCore.QRect(710, 40, 75, 23))
        self.stbt.setAutoFillBackground(False)
        self.stbt.setStyleSheet("")
        self.stbt.setCheckable(True)
        self.stbt.setAutoDefault(False)
        self.stbt.setDefault(False)
        self.stbt.setFlat(False)
        self.stbt.setObjectName("stbt")
        self.spsetbt = QtWidgets.QPushButton(self.frame)
        self.spsetbt.setGeometry(QtCore.QRect(710, 10, 75, 23))
        self.spsetbt.setObjectName("spsetbt")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setGeometry(QtCore.QRect(0, 400, 801, 191))
        self.groupBox.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.groupBox.setToolTipDuration(-1)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.printtext = QtWidgets.QTextEdit(self.groupBox)
        self.printtext.setGeometry(QtCore.QRect(0, 10, 801, 181))
        self.printtext.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.printtext.setObjectName("printtext")
        self.userlabel = QtWidgets.QLabel(self.centralwidget)
        self.userlabel.setGeometry(QtCore.QRect(700, 0, 91, 20))
        self.userlabel.setScaledContents(False)
        self.userlabel.setWordWrap(False)
        self.userlabel.setObjectName("userlabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.spsetbt.clicked.connect(MainWindow.set_spider)
        self.stbt.toggled['bool'].connect(MainWindow.spider_handle)
        self.uploadbt_1.clicked.connect(MainWindow.upload1)
        self.uploadbt_2.clicked.connect(MainWindow.upload1)
        self.uploadbt_3.clicked.connect(MainWindow.upload1)
        self.uploadbt_4.clicked.connect(MainWindow.upload1)
        self.uploadbt_5.clicked.connect(MainWindow.upload1)
        self.uploadbt_6.clicked.connect(MainWindow.upload1)
        self.uploadbt_7.clicked.connect(MainWindow.upload1)
        self.checkBox1.toggled.connect(MainWindow.cbedit1)
        self.checkBox2.toggled.connect(MainWindow.cbedit1)
        self.checkBox3.toggled.connect(MainWindow.cbedit1)
        self.checkBox4.toggled.connect(MainWindow.cbedit1)
        self.checkBox5.toggled.connect(MainWindow.cbedit1)
        self.checkBox6.toggled.connect(MainWindow.cbedit1)
        self.checkBox7.toggled.connect(MainWindow.cbedit1)

        #设置右键菜单
        self.listWidget_1.setContextMenuPolicy(3)
        #self.listWidget_1.itemClicked.connect(self.rk_menu)
        self.listWidget_1.itemDoubleClicked.connect(MainWindow.file_open)
        self.listWidget_1.customContextMenuRequested[QtCore.QPoint].connect(self.rk_menu)
        self.listWidget_2.setContextMenuPolicy(3)
        self.listWidget_2.customContextMenuRequested[QtCore.QPoint].connect(self.rk_menu)
        self.listWidget_2.doubleClicked.connect(MainWindow.file_open)
        self.listWidget_3.setContextMenuPolicy(3)
        self.listWidget_3.customContextMenuRequested[QtCore.QPoint].connect(self.rk_menu)
        self.listWidget_3.doubleClicked.connect(MainWindow.file_open)
        self.listWidget_4.setContextMenuPolicy(3)
        self.listWidget_4.customContextMenuRequested[QtCore.QPoint].connect(self.rk_menu)
        self.listWidget_4.doubleClicked.connect(MainWindow.file_open)
        self.listWidget_5.setContextMenuPolicy(3)
        self.listWidget_5.customContextMenuRequested[QtCore.QPoint].connect(self.rk_menu)
        self.listWidget_5.doubleClicked.connect(MainWindow.file_open)
        self.listWidget_6.setContextMenuPolicy(3)
        self.listWidget_6.customContextMenuRequested[QtCore.QPoint].connect(self.rk_menu)
        self.listWidget_6.doubleClicked.connect(MainWindow.file_open)
        self.listWidget_7.setContextMenuPolicy(3)
        self.listWidget_7.customContextMenuRequested[QtCore.QPoint].connect(self.rk_menu)
        self.listWidget_7.doubleClicked.connect(MainWindow.file_open)

        # 列表设置字体
        self.listWidget_1.setFont(font)
        self.listWidget_2.setFont(font)
        self.listWidget_3.setFont(font)
        self.listWidget_4.setFont(font)
        self.listWidget_5.setFont(font)
        self.listWidget_6.setFont(font)
        self.listWidget_7.setFont(font)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "笔果数据管理"))
        MainWindow.setWindowIcon(QtGui.QIcon('./ico/cm02.ico'))

        # self.tabWidget.setTabIcon(0,self.icon1)
        # self.tabWidget.setTabIcon(1, self.icon1)
        # self.tabWidget.setTabIcon(2, self.icon1)
        # self.tabWidget.setTabIcon(3, self.icon1)
        # self.tabWidget.setTabIcon(4, self.icon1)
        # self.tabWidget.setTabIcon(5, self.icon1)
        # self.tabWidget.setTabIcon(6, self.icon1)

        self.pzbt.setText(_translate("MainWindow", "配置修改"))
        self.uploadbt_1.setText(_translate("MainWindow", "开始上传"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "万题库"))
        self.pzbt_2.setText(_translate("MainWindow", "配置修改"))
        self.uploadbt_2.setText(_translate("MainWindow", "开始上传"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "自考真题库"))
        self.pzbt_3.setText(_translate("MainWindow", "配置修改"))
        self.uploadbt_3.setText(_translate("MainWindow", "开始上传"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "自考友"))
        self.pzbt_4.setText(_translate("MainWindow", "配置修改"))
        self.uploadbt_4.setText(_translate("MainWindow", "开始上传"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "答题易"))
        self.pzbt_5.setText(_translate("MainWindow", "配置修改"))
        self.uploadbt_5.setText(_translate("MainWindow", "开始上传"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "自考5网站"))
        self.pzbt_6.setText(_translate("MainWindow", "配置修改"))
        self.uploadbt_6.setText(_translate("MainWindow", "开始上传"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "百度文库"))
        self.pzbt_7.setText(_translate("MainWindow", "配置修改"))
        self.uploadbt_7.setText(_translate("MainWindow", "开始上传"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "自考365app"))
        self.checkBox1.setText(_translate("MainWindow", "万题库"))
        self.checkBox3.setText(_translate("MainWindow", "自考友"))
        self.checkBox5.setText(_translate("MainWindow", "自考5"))
        self.checkBox6.setText(_translate("MainWindow", "百度文库"))
        self.checkBox4.setText(_translate("MainWindow", "答题易"))
        self.checkBox7.setText(_translate("MainWindow", "365app"))
        self.checkBox2.setText(_translate("MainWindow", "真题库"))
        self.stbt.setText(_translate("MainWindow", "开始"))
        self.spsetbt.setText(_translate("MainWindow", "爬虫设置"))
        self.groupBox.setTitle(_translate("MainWindow", "调试信息"))
        self.userlabel.setText(_translate("MainWindow", "User"))


    def set_spider(self):
        pass

    def file_open(self,e):
        print("doublec")
        # excelapp = client.Dispatch("Excel.Application")
        # excelapp.Visible = -1
        # excelapp.Workbooks.Open("D:\workspace\project\pyqt\\biguo2\wantiku\\1.xlsx")
        # QtCore.QModelIndex
        # self.sender().setStyleSheet("QListWidget::item:selected{background:lightgray; color:green; }")
        try:
            #self.sender().item(e.row()).setForeground(QtGui.QColor('green'))
            e.setForeground(QtGui.QColor('green'))
        except Exception as re:
            print(re)

    def rk_menu(self,e):            # 弹出右键菜单
        try:
            if not self.listWidget_1.itemAt(e.x(), e.y()):
                return
           # print('弹出菜单',e.x(),e.y(),self.sender())
            a = self.sender()
            popMenu = QtWidgets.QMenu(self.listWidget_1)
            popMenu.addAction(Qt.QAction('删除',self))
            qp = Qt.QPoint(Qt.QCursor.pos().x()+1,Qt.QCursor.pos().y())
            try:
                # popMenu.triggered.connect(lambda: self.rm(a,e.x(),e.y()))
                popMenu.triggered.connect(partial(self.rm,a,e))
                # 绑定删除按钮的方法，用 partial 函数传递额外参数，还可以用匿名函数，但是匿名函数不带默认参数
            except Exception as e:
                print(e)
            popMenu.exec_(qp)

        except Exception as e:
            print(e)

    def rm(self,liw,pos,e):         # 右键菜单删除功能
        # print(liw, pos, e)
        try:
            if e.text() == "删除":
                item = liw.itemAt(pos.x(),pos.y())
                print("删除第%d行：%s" % (liw.row(item) + 1, item.text()))
                liw.removeItemWidget(liw.takeItem(liw.row(item)))

                self.flushnum()
                #liw.updateEditorData()
                #print(e.text(),e.senderSignalIndex(),self.sender())
                #QtWidgets.QMenu.at
                #QtWidgets.QAction.

        except Exception as e:
            print(e)

    def flushnum(self):              # 实时显示列表中的试卷数目。***
        self.label_11.setText(str(len(self.listWidget_1)))
        self.label_22.setText(str(len(self.listWidget_2)))
        self.label_33.setText(str(len(self.listWidget_3)))
        self.label_44.setText(str(len(self.listWidget_4)))
        self.label_55.setText(str(len(self.listWidget_5)))
        self.label_66.setText(str(len(self.listWidget_6)))
        self.label_77.setText(str(len(self.listWidget_7)))
